#!/bin/sh

ROOT=$(dirname $0)/..
DEST=${DEST:-"$ROOT/docs"}
SRC=${SRC:-"$ROOT/src"}
HEADER=${HEADER:-"$SRC/header.html"}
FOOTER=${FOOTER:-"$SRC/footer.html"}
PANOPTS=${PANOPTS:-"--highlight-style=breezedark --css $SRC/css/main.css \
--email-obfuscation=javascript -f markdown -t html5 -B $HEADER -A $FOOTER"}


RED="\033[91m"
GRN="\033[92m"
MAG="\033[95m"
BLD="\033[1m"
END="\033[0m"

warn() {
    echo "$RED$BLD$1$END"
}

fail() {
    warn $1
    exit 1
}

status() {
    echo "$MAG$1$END"
}

cd $ROOT

status "Rendering site"
status "$DEST"
