#!/bin/sh

ROOT=$(dirname $0)/..
DEST=${DEST:-"$ROOT/docs"}
SRC=${SRC:-"$ROOT/src"}
HEADER=${HEADER:-"$SRC/header.html"}
FOOTER=${FOOTER:-"$SRC/footer.html"}
PANOPTS=${PANOPTS:-"--css $SRC/css/main.css \
--email-obfuscation=javascript -f markdown -t html5 -B $HEADER -A $FOOTER"}


RED="\033[91m"
GRN="\033[92m"
MAG="\033[95m"
BLD="\033[1m"
END="\033[0m"

warn() {
    echo "$RED$BLD$1$END"
}

fail() {
    warn $1
    exit 1
}

status() {
    echo "$MAG$1$END"
}

soft_mkdir() {
   [ -d $1 ] || mkdir $1 
}

status "Rendering site"

mkdir -p $DEST

for file in `find $SRC -name "*.md" -type f` 
do 
   from="${file##$SRC}" # Strip `src` path from file string
   to="${from%%md}html"
   echo "$from --> $to"
   soft_mkdir $(dirname "$DEST$to")
   pandoc $PANOPTS --output=$DEST$to $file || warn "failed to create $to"
done
